# return the names of students and teachers in faculties with canteens that have a capacity of at least 150
PREFIX ex: <http://example.org/vocabulary/>

SELECT ?studentName ?teacherName ?facultyName ?canteenCapacity
WHERE {
  ?faculty 
    ex:facultyName ?facultyName ;
    ex:numberOfFacultyStudents ?students ;
    ex:numberOfFacultyTeachers ?teachers .

  ?student 
    ex:enrolledIn ?faculty ;
    ex:givenName ?studentName .

  ?teacher 
    ex:teachesAt ?faculty ;
    ex:givenName ?teacherName .

  ?canteen 
    ex:belongsTo ?faculty ;
    ex:capacity ?canteenCapacity .
    
  FILTER(?canteenCapacity >= 150)
}
